name 'windowsdev'
maintainer 'Prajeesh Prathap'
maintainer_email 'prajeesh.prathap@infosupport.com'
license 'all_rights'
description 'configures a windows development machine for .net development'
long_description 'configures a windows development machine for .net development'
version '0.1.3'
depends 'windows'
depends 'chocolatey'